name: "Test"

on: [push]

jobs:
  setup-sqlite:
    runs-on: ubuntu-latest
    name: Setup SQLite
    steps:
      - uses: actions/checkout@v5
      - uses: "./"
        with:
          version: "3.43.2"
      - run: sqlite3 --version
